services:
  stable-diffusion-forge:
    build: .
    container_name: stable-diffusion-forge
    image: stable-diffusion-forge-gpu
    ports:
      - "7860:7860"
    volumes:
      - ./extensions:/stable-diffusion/extensions
      - ./models:/stable-diffusion/models
      - ./outputs:/stable-diffusion/outputs
      # Keep a venv cache as a docker volume
      - venv:/stable-diffusion-webui/venv
      - repositories:/stable-diffusion/repositories
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    restart: unless-stopped
    # command: 
    #   - "./webui.sh"
    #   - "--enable-insecure-extension-access"
    #   - "--listen"
    #   - "--port" 
    #   - "7860"

# Persist venv in it's own volume
volumes:
  venv:
  repositories: